apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: taskapp-secret
  namespace: taskapp
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: taskapp-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_USER
      remoteRef:
        key: taskapp/prod
        property: database_user
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: taskapp/prod
        property: database_password
    - secretKey: POSTGRES_USER
      remoteRef:
        key: taskapp/prod
        property: database_user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: taskapp/prod
        property: database_password
    - secretKey: SECRET_KEY
      remoteRef:
        key: taskapp/prod
        property: secret_key
    - secretKey: TASKAPP_ADMIN_USERNAME
      remoteRef:
        key: taskapp/prod
        property: admin_username
    - secretKey: TASKAPP_ADMIN_PASSWORD
      remoteRef:
        key: taskapp/prod
        property: admin_password
    - secretKey: TASKAPP_DEMO_USERNAME
      remoteRef:
        key: taskapp/prod
        property: demo_username
    - secretKey: TASKAPP_DEMO_PASSWORD
      remoteRef:
        key: taskapp/prod
        property: demo_password
