apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: taskapp-backend
  namespace: taskapp
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taskapp-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: taskapp-frontend
  namespace: taskapp
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taskapp-frontend
