apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: CHANGE_ME_AWS_REGION
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: external-secrets-aws
            namespace: external-secrets
            key: access-key-id
          secretAccessKeySecretRef:
            name: external-secrets-aws
            namespace: external-secrets
            key: secret-access-key
