- name: Check k3s agent install
  ansible.builtin.stat:
    path: /etc/systemd/system/k3s-agent.service
  register: k3s_agent_service

- name: Install k3s agent
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" K3S_URL="{{ k3s_server_url }}" K3S_TOKEN="{{ hostvars[groups['k3s_servers'][0]].k3s_node_token }}" sh -s - agent \
      --node-ip "{{ private_ip }}"
  args:
    executable: /bin/bash
  when: not k3s_agent_service.stat.exists
