cluster_user: ubuntu
k3s_version: v1.30.2+k3s2
k3s_server_url: "https://{{ hostvars[groups['k3s_servers'][0]].private_ip }}:6443"
local_kubeconfig_path: "{{ playbook_dir }}/kubeconfig"
argocd_version: v2.11.4
cert_manager_version: v1.15.1
metrics_server_version: v0.7.1
cilium_cli_version: v0.16.11
